---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: prometheus-template
labels:
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/instance: ${NAME}-prometheus
  app.kubernetes.io/managed-by: kubectl
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/part-of: monitoring
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-prometheus
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app.kubernetes.io/instance: ${NAME}-prometheus
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app.kubernetes.io/component: monitoring
            app.kubernetes.io/instance: ${NAME}-prometheus
            app.kubernetes.io/managed-by: kubectl
            app.kubernetes.io/name: prometheus
            app.kubernetes.io/part-of: monitoring
        spec:
          containers:
            - name: ${NAME}-prometheus
              image: prom/prometheus:v2.30.3
              imagePullPolicy: Always
              ports:
                - containerPort: 9090
                  protocol: TCP
              volumeMounts:
                - name: ${NAME}-prometheus-config-volume
                  mountPath: /etc/prometheus/prometheus.yml
                  subPath: prometheus.yml
                - name: ${NAME}-prometheus-storage
                  mountPath: /prometheus
          volumes:
            - name: ${NAME}-prometheus-config-volume
              configMap:
                name: ${NAME}-prometheus-config
            - name: ${NAME}-prometheus-storage
              persistentVolumeClaim:
                claimName: ${NAME}-prometheus
      triggers:
        - type: ConfigChange
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${NAME}-prometheus
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${PROMETHEUS_VOLUME_CAPACITY}
      storageClassName: netapp-file-standard
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}-prometheus
    spec:
      ports:
        - name: 9090-tcp
          port: 9090
          protocol: TCP
          targetPort: 9090
      selector:
        app.kubernetes.io/instance: ${NAME}-prometheus
      type: ClusterIP
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all objects in this template.
    required: true
    value: monitoring
  - name: PROMETHEUS_VOLUME_CAPACITY
    displayName: Prometheus Volume Capacity
    description: The volume capacity for Prometheus
    required: true
    value: 2Gi
